# -*- coding: utf-8 -*-
"""adaptive_reward_rl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTkm78B2wM-1cdEZ7SzrcMVhOyp_zYJ-
"""

!pip install stable-baselines3 gymnasium torch matplotlib

import gymnasium as gym
from gymnasium import spaces
import numpy as np

class CoinEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.grid_size = 5
        self.action_space = spaces.Discrete(4)
        self.observation_space = spaces.Box(low=0, high=4, shape=(2,), dtype=np.int32)

    def reset(self, seed=None, options=None):
        # super().reset(seed=seed) # Removed to avoid potential NoneType issue
        self.agent_pos = np.array([0, 0])
        self.coin_pos = np.array([2, 2])
        return self.agent_pos.astype(np.float32), {}

    def step(self, action):
        if action == 0: self.agent_pos[0] -= 1
        if action == 1: self.agent_pos[0] += 1
        if action == 2: self.agent_pos[1] -= 1
        if action == 3: self.agent_pos[1] += 1

        self.agent_pos = np.clip(self.agent_pos, 0, self.grid_size - 1)

        reward = 0
        if np.array_equal(self.agent_pos, self.coin_pos):
            reward = 1  # exploitable

        return self.agent_pos.astype(np.float32), reward, False, False, {}

class AdaptiveCoinEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.grid_size = 5
        self.action_space = spaces.Discrete(4)
        self.observation_space = spaces.Box(low=0, high=4, shape=(2,), dtype=np.int32)

    def reset(self, seed=None, options=None):
        # super().reset(seed=seed)   # Removed to avoid potential NoneType issue

        self.agent_pos = np.array([0, 0], dtype=np.float32)
        self.coin_pos = np.array([2, 2], dtype=np.float32)
        self.visited = {} if hasattr(self, "visited") else {}

        self.steps = 0  # for episode control

        return self.agent_pos, {}   # MUST RETURN THIS

    # Corrected indentation for step method
    def step(self, action):
        if action == 0: self.agent_pos[0] -= 1
        if action == 1: self.agent_pos[0] += 1
        if action == 2: self.agent_pos[1] -= 1
        if action == 3: self.agent_pos[1] += 1

        self.agent_pos = np.clip(self.agent_pos, 0, self.grid_size - 1)

        pos = tuple(self.agent_pos)
        self.visited[pos] = self.visited.get(pos, 0) + 1

        reward = 0
        if np.array_equal(self.agent_pos, self.coin_pos):
            reward = 1

        # 🔥 YOUR INNOVATION
        if self.visited[pos] > 3:
            reward -= 0.5

        return self.agent_pos.astype(np.float32), reward, False, False, {}

from stable_baselines3 import PPO

baseline_env = CoinEnv()
baseline_model = PPO("MlpPolicy", baseline_env, verbose=0)
baseline_model.learn(total_timesteps=10000)

adaptive_env = AdaptiveCoinEnv()
adaptive_model = PPO("MlpPolicy", adaptive_env, verbose=0)
adaptive_model.learn(total_timesteps=10000)

def evaluate(env, model, steps=100):
    obs, _ = env.reset()
    total_reward = 0
    visited = []

    for _ in range(steps):
        action, _ = model.predict(obs)
        obs, reward, done, _, _ = env.step(action)
        total_reward += reward
        visited.append(tuple(obs))

    return total_reward, visited

baseline_reward, baseline_path = evaluate(CoinEnv(), baseline_model)
adaptive_reward, adaptive_path = evaluate(AdaptiveCoinEnv(), adaptive_model)

print("Baseline Reward:", baseline_reward)
print("Adaptive Reward:", adaptive_reward)

import matplotlib.pyplot as plt

def plot_paths_comparison(paths_data, title):
    plt.figure(figsize=(10, 8))
    for path, label in paths_data:
        x = [p[0] for p in path]
        y = [p[1] for p in path]
        plt.plot(x, y, marker='o', label=label, alpha=0.7)

    plt.title(title)
    plt.xlim(0,4)
    plt.ylim(0,4)
    plt.grid()
    plt.legend()
    plt.show()

# Prepare data for the comparison plot
paths_to_plot = [
    (baseline_path, "Baseline Agent Path"),
    (adaptive_path, "Adaptive Agent Path")
]

plot_paths_comparison(paths_to_plot, "Baseline vs. Adaptive Agent Paths")

from stable_baselines3 import PPO

baseline_env = CoinEnv()
baseline_model = PPO("MlpPolicy", baseline_env, verbose=0)
baseline_model.learn(total_timesteps=10000)

adaptive_env = AdaptiveCoinEnv()
adaptive_model = PPO("MlpPolicy", adaptive_env, verbose=0)
adaptive_model.learn(total_timesteps=10000)

def evaluate(env, model, steps=100):
    obs, _ = env.reset()
    total_reward = 0
    visited = []

    for _ in range(steps):
        action, _ = model.predict(obs)
        obs, reward, done, _, _ = env.step(action)
        total_reward += reward
        visited.append(tuple(obs))

    return total_reward, visited

baseline_reward, baseline_path = evaluate(CoinEnv(), baseline_model)
adaptive_reward, adaptive_path = evaluate(AdaptiveCoinEnv(), adaptive_model)

print("Baseline Reward:", baseline_reward)
print("Adaptive Reward:", adaptive_reward)

import matplotlib.pyplot as plt

def plot_path(path, title):
    x = [p[0] for p in path]
    y = [p[1] for p in path]

    plt.plot(x, y, marker='o')
    plt.title(title)
    plt.xlim(0,4)
    plt.ylim(0,4)
    plt.grid()
    plt.show()

plot_path(baseline_path, "Baseline Agent Path (Reward Hacking)")
plot_path(adaptive_path, "Adaptive Agent Path (Fixed Behavior)")